.PHONY: clean All

All:
	@echo "----------Building project:[ MystringMOVE - Debug ]----------"
	@cd "MystringMOVE" && "$(MAKE)" -f  "MystringMOVE.mk"
clean:
	@echo "----------Cleaning project:[ MystringMOVE - Debug ]----------"
	@cd "MystringMOVE" && "$(MAKE)" -f  "MystringMOVE.mk" clean
